services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - ${NGROK_PORT}:5678
    environment:
      TZ: "Asia/Manila"
      GENERIC_TIMEZONE: "Asia/Manila"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES: "false"
      # Uncomment after setting up ngrok with:
      # ngrok http 6789
      EDITOR_BASE_URL: ${NGROK_URL}
      WEBHOOK_URL: ${NGROK_URL}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/home/node/.n8n-files/files/:ro

volumes:
  n8n_data: