services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - 6789:5678
    environment:
      TZ: "Asia/Manila"
      GENERIC_TIMEZONE: "Asia/Manila"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      # Uncomment after setting up ngrok with:
      # ngrok http 6789
      EDITOR_BASE_URL: https://chieko-nonvisiting-konnor.ngrok-free.dev 
      WEBHOOK_URL: https://chieko-nonvisiting-konnor.ngrok-free.dev 
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/files:ro

volumes:
  n8n_data: